<a href="https://colab.research.google.com/github/rallm/IUST-DL-Fall2025/blob/main/HW1/ans/hw1_p2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [4]:
z = np.array([1.5, 2.8, 3.1, 1.0, 2.5]).reshape(5, 1)
z

array([[1.5],
       [2.8],
       [3.1],
       [1. ],
       [2.5]])

In [5]:
z_exp = np.exp(z)
z_exp

array([[ 4.48168907],
       [16.44464677],
       [22.19795128],
       [ 2.71828183],
       [12.18249396]])

In [7]:
sum_exp_xj = np.sum(z_exp)
print(sum_exp_xj)

58.025062912039274


In [8]:
softmax_results = z_exp / sum_exp_xj
softmax_results

array([[0.07723713],
       [0.28340593],
       [0.38255799],
       [0.04684668],
       [0.20995227]])

In [10]:
y = np.zeros((5, 1))
y[3, 0] = 1
y

array([[0.],
       [0.],
       [0.],
       [1.],
       [0.]])

In [12]:
cross_entropy = -np.sum(y * np.log(softmax_results + 1e-10))
print(cross_entropy)

3.060875034248285
